CREATE TABLE "trades" (
	"id" serial PRIMARY KEY NOT NULL,
	"instrument" text NOT NULL,
	"session" text NOT NULL,
	"market_bias" text NOT NULL,
	"bias_notes" text,
	"order_type" text NOT NULL,
	"direction" text NOT NULL,
	"entry_price" numeric(10, 2) NOT NULL,
	"stop_loss" numeric(10, 2),
	"take_profit" numeric(10, 2),
	"exit_price" numeric(10, 2),
	"lot_size" numeric(10, 4) NOT NULL,
	"start_balance" numeric(10, 2) NOT NULL,
	"current_equity" numeric(10, 2) NOT NULL,
	"pnl" numeric(10, 2),
	"pnl_percentage" numeric(5, 2),
	"risk_percentage" numeric(5, 2),
	"rr_ratio" numeric(5, 2),
	"status" text DEFAULT 'open' NOT NULL,
	"exit_reason" text,
	"trend_analysis" text,
	"indicators" text,
	"partial_tp_enabled" boolean DEFAULT false,
	"partial_tp_percentage" numeric(5, 2),
	"partial_tp_price" numeric(10, 2),
	"notes" text,
	"entry_date" timestamp DEFAULT now() NOT NULL,
	"exit_date" timestamp
);
